package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import android.support.v7.app.AppCompatActivity
import android.util.Log
import android.view.View
import android.widget.Button
import ca.csf.mobile2.tp2.R
import org.androidannotations.annotations.*

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@EActivity(R.layout.activity_question)
class QuestionActivity : AppCompatActivity() {

    //View items
    /*@ViewById(R.id.choice1_button)
    protected lateinit var choice1_button : Button
    @ViewById(R.id.choice2_button)
    protected lateinit var choice2_button : Button
    @ViewById(R.id.choice1_result_background)
    protected lateinit var choice1_result_background : Button
    @ViewById(R.id.choice2_result_background)
    protected lateinit var choice2_result_background : Button
    @ViewById(R.id.choice1_result_textview)
    protected lateinit var choice1_result_textview : Button
    @ViewById(R.id.choice2_result_textview)
    protected lateinit var choice2_result_textview : Button
    @ViewById(R.id.choice1_textview)
    protected lateinit var choice1_textview : Button
    @ViewById(R.id.choice2_textview)
    protected lateinit var choice2_textview : Button
    @ViewById(R.id.error_imageview)
    protected lateinit var error_imgeview : Button
    @ViewById(R.id.error_textview)
    protected lateinit var error_textview : Button
    @ViewById(R.id.retry_button)
    protected lateinit var retry_button : Button
    @ViewById(R.id.progressBar)
    protected lateinit var progressBar : Button*/

    @Bean
    protected lateinit var questionService: QuestionService
    @AfterViews
    fun afterViews(){
        //hideAllView()
        questionService.getRandomQuestion(this::test,this::error,this::error)

    }

    @UiThread
    fun test(questionOutputDTO: QuestionOutputDTO){
        Log.e("test",questionOutputDTO.choice1)
    }

    @UiThread
    fun error(){

    }
/*
    fun hideAllView(){
        hideChoiceView()
        hideErrorView()
        hideProgressBar()
        hideRetryButton()
    }

    fun hideChoiceView(){
        choice1_button.visibility = View.INVISIBLE
        choice1_result_background.visibility = View.INVISIBLE
        choice1_result_textview.visibility = View.INVISIBLE
        choice1_textview.visibility = View.INVISIBLE
        choice2_button.visibility = View.INVISIBLE
        choice2_result_background.visibility = View.INVISIBLE
        choice2_result_textview.visibility = View.INVISIBLE
        choice2_textview.visibility = View.INVISIBLE
    }

    fun showChoiceView(){
        choice1_button.visibility = View.VISIBLE
        choice1_result_background.visibility = View.VISIBLE
        choice1_result_textview.visibility = View.VISIBLE
        choice1_textview.visibility = View.VISIBLE
        choice2_button.visibility = View.VISIBLE
        choice2_result_background.visibility = View.VISIBLE
        choice2_result_textview.visibility = View.VISIBLE
        choice2_textview.visibility = View.VISIBLE
    }

    fun showRetryButton(){
        retry_button.visibility = View.VISIBLE
    }
    fun hideRetryButton(){
        retry_button.visibility = View.INVISIBLE
    }

    fun showProgressBar(){
        progressBar.visibility = View.VISIBLE
    }
    fun hideProgressBar(){
        progressBar.visibility = View.INVISIBLE
    }

    fun hideErrorView(){
        error_imgeview.visibility = View.INVISIBLE
        error_textview.visibility = View.INVISIBLE
    }

    fun showErrorView(){

        error_imgeview.visibility = View.VISIBLE
        error_textview.visibility = View.VISIBLE
    }*/
}
